import { useTheme } from '../../context/ThemeContext.js';

export function KPICard({ label, value, sub, color, bg, icon }) {
  const C = useTheme();
  return (
    <div className="kpi-card" style={{ background:C.card, borderColor:C.border }}>
      <div className="kpi-card-inner">
        <div>
          <div className="kpi-label" style={{ color:C.muted }}>{label}</div>
          <div className="kpi-value" style={{ color:C.text }}>{value}</div>
          <div className="kpi-sub"   style={{ color:C.muted }}>{sub}</div>
        </div>
        <div className="kpi-icon" style={{ background:bg }}>{icon}</div>
      </div>
      <div className="kpi-bar" style={{ background:color }} />
    </div>
  );
}

export function Section({ title, subtitle, children, span = 1 }) {
  const C = useTheme();
  return (
    <div className={`section-card${span === 2 ? ' span-2' : ''}`} style={{ background:C.card, borderColor:C.border }}>
      <div className="section-header" style={{ borderBottomColor:C.divider }}>
        <div className="section-title"    style={{ color:C.text }}>{title}</div>
        {subtitle && <div className="section-subtitle" style={{ color:C.muted }}>{subtitle}</div>}
      </div>
      {children}
    </div>
  );
}

export function CustomTooltip({ active, payload, label }) {
  const C = useTheme();
  if (!active || !payload?.length) return null;
  return (
    <div style={{ background:C.tooltip, border:`1px solid ${C.border}`, borderRadius:8, padding:'10px 14px', fontSize:12, boxShadow:C.shadow }}>
      <div style={{ color:C.muted, marginBottom:5, fontWeight:500 }}>{label}</div>
      {payload.map((p, i) => (
        <div key={i} style={{ color:p.color || C.text, marginBottom:2 }}>
          {p.name}: <strong>{typeof p.value === 'number' ? p.value.toLocaleString('en-IN') : p.value}</strong>
        </div>
      ))}
    </div>
  );
}

export function ThemeToggle({ dark, onToggle }) {
  const C = useTheme();
  return (
    <button className="theme-toggle" onClick={onToggle}
      style={{ border:`1px solid ${C.border}`, background:C.card, color:C.muted }}>
      <div className="toggle-track" style={{ background: dark ? C.accent : C.border }}>
        <div className="toggle-knob" style={{ left: dark ? 19 : 3 }} />
      </div>
      <span>{dark ? '🌙 Dark' : '☀️ Light'}</span>
    </button>
  );
}

export function AICard({ icon, title, desc, badge }) {
  const C = useTheme();
  return (
    <div className="ai-feature-card" style={{ background:C.accentBg, borderColor:C.accentBdr }}>
      <div className="ai-feature-header">
        <span className="ai-feature-icon">{icon}</span>
        <span className="ai-badge" style={{ background:C.accentBdr, color:C.accent }}>{badge}</span>
      </div>
      <div className="ai-feature-title" style={{ color:C.text }}>{title}</div>
      <div className="ai-feature-desc"  style={{ color:C.muted }}>{desc}</div>
    </div>
  );
}

/** Server-side chart rendered as <img> from base64 PNG */
export function ServerChart({ src, title, subtitle }) {
  const C = useTheme();
  if (!src) return null;
  return (
    <Section title={title} subtitle={subtitle}>
      <img src={src} alt={title} style={{ width:'100%', borderRadius:8, display:'block' }} />
      <div style={{ fontSize:10, color:C.faint, marginTop:6, textAlign:'right' }}>
        Generated by Matplotlib · Python backend
      </div>
    </Section>
  );
}
